//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AerosoftCRJInteractionFixer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AerosoftCRJInteractionFixer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Template Name = &quot;ASCRJ_Knob_Infinite_Push_Template&quot;&gt;
        ///	&lt;DefaultTemplateParameters&gt;
        ///		&lt;CLOCKWISE_CONDITION&gt;1&lt;/CLOCKWISE_CONDITION&gt;
        ///		&lt;ANTICLOCKWISE_CONDITION&gt;1&lt;/ANTICLOCKWISE_CONDITION&gt;
        ///		&lt;KNOB_CHANGE_NAME&gt;#KNOB_ANIM_NAME#_CHANGE&lt;/KNOB_CHANGE_NAME&gt;
        ///		&lt;PUSH_NAME&gt;#PUSH_ANIM_NAME#&lt;/PUSH_NAME&gt;
        ///		&lt;KNOB_WWISE_EVENT&gt;AMB_Knob_Turn&lt;/KNOB_WWISE_EVENT&gt;
        ///		&lt;PUSH_WWISE_EVENT&gt;AMB_Switch_Off&lt;/PUSH_WWISE_EVENT&gt;
        ///		&lt;COUNT&gt;36&lt;/COUNT&gt;
        ///		&lt;DIRECTION&gt;Both&lt;/DIRECTION&gt;
        ///		&lt;ACTION&gt;Play&lt;/ACTION&gt;
        ///		&lt;ANIM_LENGTH_PUSH&gt;10&lt;/ANIM_L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ASCRJ_Knob_Infinite_Push_Template {
            get {
                return ResourceManager.GetString("ASCRJ_Knob_Infinite_Push_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ModelBehaviorModifications {
            get {
                object obj = ResourceManager.GetObject("ModelBehaviorModifications", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aerosoft CRJ Interaction Fixer
        ///==============================
        ///
        ///This application will generate a new package in your Microsoft Flight Simulator community folder which will fix the interaction issues with the MSFS Aerosoft CRJ introduced in Sim Update 5. No edits will be made to the original &apos;{OriginalPackageName}&apos; package during this process. This fix can be completely undone by removing the &apos;{PatchPackageName}&apos; package from your community folder.
        ///
        ///Requirements: Aerosoft CRJ {OriginalPackageVersionRequi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
